(function(g){var window=this;'use strict';var Ptb=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.uib)("0",Math.max(0,b-c))+a},Qtb=function(){return{I:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{I:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},Rtb=function(){return{I:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{I:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},Ttb=function(a){"number"===typeof a?(this.date=Stb(a,0,1),x6(this,1)):g.bb(a)?(this.date=Stb(a.getFullYear(),a.getMonth(),a.getDate()),x6(this,a.getDate())):(this.date=new Date(g.kb()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),x6(this,a))},Stb=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},x6=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},y6=function(a,b){g.jU.call(this,a,{I:"div",
S:"ytp-reminder-menu",X:{role:"menu",tabindex:"-1"},V:[{I:"div",S:"ytp-reminder-menu-contents",V:[{I:"div",S:"ytp-reminder-menu-items"}]}]},100,!0);this.buttonElement=b;this.j=[];this.menuPopupRenderer=void 0;this.items=this.Ea("ytp-reminder-menu-items");this.hide()},Utb=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},z6=function(a){g.V.call(this,{I:"div",
V:[{I:"button",Ka:["ytp-offline-slate-button","ytp-button"],V:[{I:"div",S:"ytp-offline-slate-button-icon",xa:"{{icon}}"},{I:"div",S:"ytp-offline-slate-button-text",xa:"{{text}}"}]}]});this.J=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.B=void 0;this.D=this.j=null;(this.buttonElement=this.Ea("ytp-offline-slate-button"))&&this.T(this.buttonElement,"click",this.G);this.hide()},Wtb=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=
b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.U(c,Vtb)?a.upcomingEventReminderButtonRenderer=g.U(c,Vtb):c&&g.U(c,Vtb)||(a.upcomingEventReminderButtonRenderer=null);A6(a)},A6=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.GF(b.toggledText):"";a.update({text:c,icon:Xtb(b.toggledIcon)})}else c=b.defaultText?g.GF(b.defaultText):"",a.update({text:c,icon:Xtb(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=Ytb(a))?(c=b.text?g.GF(b.text):"",a.update({text:c,icon:Xtb(b.icon)}),a.show()):a.hide():a.hide()},$tb=function(a,b,c){a.D||(a.D=new g.aE(a.J.U().rl));
var d={context:g.Isa(a.D.config_||g.BD())};g.$E()&&(d.context.clientScreenNonce=g.$E());d.params=c;g.bE(a.D,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.B&&(a.upcomingEventReminderButtonRenderer.currentState=a.B,a.B=void 0)},
onError:function(){Ztb(a)},
onTimeout:function(){Ztb(a)}})},Ztb=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,A6(a)):a.upcomingEventReminderButtonRenderer&&(a.B=void 0,A6(a))},Xtb=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return Qtb();case "NOTIFICATIONS_NONE":return Rtb();case "NOTIFICATIONS_ACTIVE":return g.fxa();default:return null}},Ytb=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.B||a.upcomingEventReminderButtonRenderer.currentState;a=g.u(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.U(c.value,aub))&&c.state===b&&c.button&&g.U(c.button,g.DM))return g.U(c.button,g.DM);return null},bub=function(a){g.V.call(this,{I:"div",
S:"ytp-offline-slate",V:[{I:"div",S:"ytp-offline-slate-background"},{I:"div",S:"ytp-offline-slate-bar",V:[{I:"span",S:"ytp-offline-slate-icon",V:[{I:"svg",X:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},V:[{I:"path",X:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{I:"circle",X:{cx:"12",cy:"12",r:"3"}}]}]},{I:"span",S:"ytp-offline-slate-messages",V:[{I:"div",S:"ytp-offline-slate-main-text",X:{"aria-label":"{{label}}"},xa:"{{mainText}}"},{I:"div",S:"ytp-offline-slate-subtitle-text",xa:"{{subtitleText}}"}]},{I:"span",S:"ytp-offline-slate-buttons"}]},{I:"button",Ka:["ytp-offline-slate-close-button","ytp-button"],V:[g.JF()]},{I:"button",Ka:["ytp-offline-slate-open-button","ytp-button"],V:[g.IF()]}]});var b=this;this.api=a;this.j=this.B=null;this.background=this.Ea("ytp-offline-slate-background");
this.C=this.Ea("ytp-offline-slate-bar");this.G=new g.dv(function(){g.qv(b.C,"ytp-offline-slate-bar-fade")},15E3);
this.K=!1;this.D=new g.dv(function(){g.qv(b.element,"ytp-offline-slate-collapsed")},15E3);
g.O(this,this.D);g.O(this,this.G);this.countdownTimer=new g.dv(this.G1,1E3,this);this.T(a,"presentingplayerstatechange",this.K1);this.T(a,"livestatedata",this.Ra);a=this.Ea("ytp-offline-slate-close-button");this.T(a,"click",function(){g.qv(b.element,"ytp-offline-slate-collapsed")});
a=this.Ea("ytp-offline-slate-open-button");this.T(a,"click",function(){g.tv(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Ra(a);a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().Sl;var c=8===this.api.getPresentingPlayerType();g.vv(this.element,"ytp-offline-slate-premiere-trailer",a);g.vv(this.element,"ytp-offline-slate-hide-background",c)},cub=function(a,b,c){if(b){var d=null!=b.subtitleText?g.GF(b.subtitleText):"";
c=c?c:null!=b.mainText?g.GF(b.mainText):"";var e,f,h,l;b=null!=(l=null==(e=b.mainText)?void 0:null==(f=e.accessibility)?void 0:null==(h=f.accessibilityData)?void 0:h.label)?l:c;a.update({mainText:c,subtitleText:d,label:b});g.vv(a.element,"ytp-offline-slate-single-text-line",!d);g.vv(a.C,"ytp-offline-slate-bar-hidden",!c&&!d)}},B6=function(a,b){var c=(0,g.ZC)();
this.module="heartbeat";this.trigger=a;this.j=b;this.C=c},kub=function(a){g.uV.call(this,a);
var b=this;this.N=!1;this.Z=0;this.G=!1;this.B=new g.dv(function(){var e=b.player.U(),f=b.getVideoData();C6(b)&&(dub(b)?eub(b,e,f):(fub(b),gub(b,e,f)))},0);
this.j=this.heartbeatParams=null;this.D=!1;this.K=new g.Nl(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.oa=new g.aE(void 0);this.Y=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new Ttb).getTimezoneOffset();this.C=new g.xK(this);g.O(this,this.B);g.O(this,this.C);fub(this);hub(this);this.C.T(a,"heartbeatparams",this.cF);this.C.T(a,"presentingplayerstatechange",this.y3);this.C.T(a,"videoplayerreset",this.z3);this.C.T(a,g.GJ("heartbeat"),this.onCueRangeEnter);this.D&&this.j&&
iub(this,void 0,this.j);var c=new g.FJ(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.FJ(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.rf([c,d]);jub(this)},jub=function(a){var b=a.getVideoData();
b.Ml&&(b=b.botguardData)&&g.ONa(b,a.player.U())},fub=function(a){var b=a.getVideoData();
if(b.Ml&&(b=new g.MNa(b),g.gP.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.yq){var d=g.NNa(b);if(d){c={};var e={};d=d.split("&");d=g.u(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=lub[Number(e.r1c)]);c.challenge=b.videoData.yq}}a.attestationResponse=c||void 0}},dub=function(a){var b=a.getVideoData();
if(!g.jT(a.getVideoData())||b.Z1)return!1;if(b.useInnertubeDrmService()&&b.K){a="playready"===b.K.flavor&&b.L("html5_innertube_heartbeats_for_playready");var c="widevine"===b.K.flavor&&b.L("html5_innertube_heartbeats_for_widevine");b=g.lR(b.K)&&b.L("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},mub=function(a){if(dub(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.jT(a.getVideoData())&&b.useInnertubeDrmService()&&!b.Il&&!b.FC?!1:!!b.heartbeatToken},D6=function(a,b){if(!a.B.isActive()&&a.N){var c=a.getVideoData();
if(mub(a)||c.isLivePlayback){if(void 0===b)if(a.G)if(a.D)b=7500;else{var d;b=(null==(d=a.heartbeatParams)?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().h0||6E4}else b=1E3;a.B.start(b)}}},qub=function(a,b,c){b.Wm&&(c=g.jn(c,{internalipoverride:b.Wm}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.Eb&&(d.kpt=b.Eb);c=g.jn(c,d);g.AB(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.B.isActive()&&C6(a)){a.K.reset();a.sequenceNumber++;e=e.responseText;var f=nub(e);if(f){a.player.gb("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(oub))?"0"===h[1]?0:1:-1;pub(a,void 0,f,e,h)}},
onError:function(e){C6(a)&&E6(a,!0,"net-"+e.status)},
onTimeout:function(){C6(a)&&E6(a,!0,"timeout")},
withCredentials:!0})},eub=function(a,b,c){var d;
if(null!=(d=a.heartbeatParams)&&d.url){var e=g.jn(a.heartbeatParams.url,{request_id:g.cua()});c.Ba&&(e=g.jn(e,{vvt:c.Ba}),c.mdxEnvironment&&(e=g.jn(e,{mdx_environment:c.mdxEnvironment})));g.jS(b,c.oauthToken).then(function(f){f&&(e=g.jn(e,{access_token:f}));qub(a,c,e)})}},C6=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.lG(a.player.Tb(a.getPlayerType()),4)?!1:mub(a)||b.isLivePlayback?!0:(F6(a),!1)},gub=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!=(d=a.ra)?d:c.heartbeatServerData};a.Y=a.attestationResponse;c.Ml&&(e.attestationResponse=a.Y);var f=g.IT(c),h;d=null!=(h=f.client)?h:{};d.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)d.timeZone=h;h={heartbeatChecks:[]};if(d=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),(d=d.playabilityStatus)&&
(d=d.liveStreamability)&&d.liveStreamabilityRenderer&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.hJ(b)){h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");f=rub(a);d={};null!==f&&(d.clientPlayerPositionUtcMillis=f);var l,m;f=(null==(m=null==(l=a.player.xb())?void 0:g.JV(l))?void 0:m.freePreviewWatchedDuration)||0;0<f&&(d.freePreviewWatchedDuration={seconds:""+f});h.unpluggedParams=d}e.heartbeatRequestParams=
h;c.isLivePlayback?(l=rub(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={utcTimeMillis:l})):b.L("enable_heartbeat_vod_playback_position")&&(l=sub(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={streamTimeMillis:l}));a.player.publish("heartbeatRequest",e);var n={timeout:3E4,onSuccess:function(p){if(!a.B.isActive()&&C6(a)){var q=a.getVideoData(),r=q.Ml&&null==a.Y,t;q.Ml=!(null==(t=p.heartbeatAttestationConfig)||!t.requiresAttestation)||
r;r=p.playabilityStatus;t=JSON.stringify(r)||"{}";p.authenticationMismatch&&a.player.ma("authshear",{});var v=-1;var w=p.playabilityStatus;w&&(a.player.gb("onHeartbeat",w),"OK"===w.status?v=p.stopHeartbeat?2:0:"UNPLAYABLE"===w.status?v=1:"LIVE_STREAM_OFFLINE"===w.status&&(v=0));a.sequenceNumber&&-1===v||a.K.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.ra=p.heartbeatServerData);q.HC=p;(w=p.playerCueRangeSet)&&g.NTa(q,w);p.playerCueRanges&&0<p.playerCueRanges.length&&(q.cueRanges=p.playerCueRanges);
var A,D;(null==(A=p.progressBarConfig)?0:A.progressBarStartPosition)&&(null==(D=p.progressBarConfig)?0:D.progressBarEndPosition)&&(q.progressBarStartPosition=p.progressBarConfig.progressBarStartPosition,q.progressBarEndPosition=p.progressBarConfig.progressBarEndPosition);q.compositeLiveIngestionOffsetToken=p.compositeLiveIngestionOffsetToken;p.compositeLiveStatusToken!==q.compositeLiveStatusToken&&(q.compositeLiveStatusToken=p.compositeLiveStatusToken);q.publish("dataupdated");pub(a,p,r,t,v)}},
onError:function(p){C6(a)&&E6(a,!0,"net-"+p.status)},
onTimeout:function(){C6(a)&&E6(a,!0,"timeout")}};
g.jS(b,g.AT(c)).then(function(p){p&&(n.NV="Bearer "+p);g.bE(a.oa,"player/heartbeat",e,n)})},pub=function(a,b,c,d,e){-1===e?(c="decode "+g.Kg(d,3),E6(a,!1,c)):2===e?(F6(a),a.G=!0):(a.Z=0,a.B.stop(),1===e?(a.G=!1,c&&"PLAYABILITY_ERROR_CODE_EMBARGOED"===c.errorCode&&a.player.xo(!0),e="pe."+(null==c?void 0:c.errorCode)+";ps."+(null==c?void 0:c.status),a.player.gg("heartbeat.stop",2,a.Bf(d),e),g.LC("heartbeatActionPlayerHalted",tub(c)),(null==b?0:b.videoTransitionEndpoint)&&c&&(b=b.videoTransitionEndpoint,
(d=g.U(b,g.ZS))&&uub(a,d,c,{itct:null==b?void 0:b.clickTrackingParams}))):(a.G=!0,d=0,a.D&&c&&(d=iub(a,b,c),a.player.publish("livestatedata",c)),d?D6(a,d):D6(a)))},iub=function(a,b,c){var d=c.liveStreamability&&c.liveStreamability.liveStreamabilityRenderer,e=!(!d||!(d.switchStreamsImmediately||d.transitionTiming&&"STREAM_TRANSITION_TIMING_IMMEDIATELY"===d.transitionTiming));
b=vub(a,b,d);var f=a.getVideoData(),h=a.player.Tb(a.getPlayerType()),l=h.isPlaying()&&!g.pT(f)&&!a.player.isAtLiveHead(a.getPlayerType());if(f.U().Ic()){var m,n=(null==(m=a.player.jf())?void 0:m.lc())||{};n.status=c.status||"";n.dvr=""+ +l;n["switch"]=""+ +e;n.ended=""+ +!(!d||!d.displayEndscreen);a.player.ma("heartbeat",n)}if(l&&!e)return b;e=d&&d.streamTransitionEndpoint&&g.U(d.streamTransitionEndpoint,g.ZS);if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(d&&d.transitionTiming))a.getVideoData().transitionEndpointAtEndOfStream=
e;else if(e&&uub(a,e,c))return b;if("OK"===c.status.toUpperCase()){e=d&&d.broadcastId;m=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;l=e!==m&&null!=e;if(!g.mT(f)||l){var p={video_id:f.videoId};f.OC&&(p.is_live_destination="1");a.player.L("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.getWatchNextResponse());p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;
p.force_gvi=f.Vm;p.Cm=f.Cm;f.G&&(p.vss_credentials_token=f.G,p.vss_credentials_token_type=f.Pm);f.Ba&&(p.vvt=f.Ba);d=void 0;g.mT(f)?l&&(d=new B6("broadcastIdChanged",m+","+e),a.tJ("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",c)):(e&&(d=new B6("formatsReceived",""+e)),a.tJ("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",c));a.player.loadVideoByPlayerVars(p,void 0,void 0,void 0,d);return b}a.player.Hg("heartbeat",
a.getPlayerType())}d&&d.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.K=!0,a.Cb&&a.api.AB()):g.sL(h)&&(f=(null==(p=a.player.jf())?void 0:p.lc())||{},a.player.ma("hbse",f,!0),a.player.AB(),a.player.gb("onLiveMediaEnded",c)));return b},vub=function(a,b,c){return a.player.L("web_player_use_heartbeat_poll_delay_ms")&&(a=Number(null==b?void 0:b.pollDelayMs))?a:(c=Number(null==c?void 0:c.pollDelayMs))?c:0},E6=function(a,b,c){var d=a.player.U();
if(!a.B.isActive()){a.B.stop();a.Z++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.X0||b&&!g.jT(a.getVideoData())&&!mub(a)&&f.isLivePlayback)f=!1;else{var h,l;(null==(l=a.heartbeatParams)?0:l.retries)?h=a.heartbeatParams.retries:h=f.A0||5;f=a.Z>=h}f?(g.LC("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:tub()),(b=a.getVideoData())&&b.isLivePlayback?a.player.gg(e,1,"Reprodu\u00e7\u00e3o de v\u00eddeo interrompida. Tente novamente.",c):a.player.gg(e,
1,"Ocorreu um erro ao licenciar este v\u00eddeo.",c)):(d.L("html5_report_non_fatal_heartbeat_error")&&a.player.Kr(e,{msg:c}),D6(a,a.K.getValue()),g.Ol(a.K))}},tub=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},F6=function(a){a.Z=0;
a.B.stop();a.G=!1;a.sequenceNumber=0},hub=function(a){var b=a.getVideoData(),c=a.player.U();
if(b.isLivePlayback)if(g.yRa(c.G)){a.D=!0;a.N=!0;if(!g.jJ(c)||g.hJ(c))a.offlineSlate=new bub(a.player),g.O(a,a.offlineSlate),g.fU(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;"UNPLAYABLE"!==(null==(d=a.j)?void 0:d.status)&&(a.j?(d=vub(a,void 0,a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?D6(a,d):D6(a,7500):D6(a,1E3))}else a.player.gg("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.Fb(b.Da,"heartbeat")&&a.player.Hg("heartbeat",a.getPlayerType())},uub=function(a,b,c,d){var e=b&&b.videoId;
return e?(a.player.Lo(e,Object.assign({},{autonav:"1"},d||{}),void 0,!0,!0,b,g.AT(a.getVideoData())),a.tJ("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",c),!0):!1},rub=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},sub=function(a){return(a=a.player.getCurrentTime(a.getPlayerType()))&&isFinite(a)?""+Math.floor(1E3*a):null},nub=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},wub={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
wub={ERAS:["a.C.","d.C."],ERANAMES:["antes de Cristo","depois de Cristo"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"janeiro fevereiro mar\u00e7o abril maio junho julho agosto setembro outubro novembro dezembro".split(" "),STANDALONEMONTHS:"janeiro fevereiro mar\u00e7o abril maio junho julho agosto setembro outubro novembro dezembro".split(" "),SHORTMONTHS:"jan. fev. mar. abr. mai. jun. jul. ago. set. out. nov. dez.".split(" "),STANDALONESHORTMONTHS:"jan. fev. mar. abr. mai. jun. jul. ago. set. out. nov. dez.".split(" "),
WEEKDAYS:"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),STANDALONEWEEKDAYS:"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),SHORTWEEKDAYS:"dom. seg. ter. qua. qui. sex. s\u00e1b.".split(" "),STANDALONESHORTWEEKDAYS:"dom. seg. ter. qua. qui. sex. s\u00e1b.".split(" "),NARROWWEEKDAYS:"DSTQQSS".split(""),STANDALONENARROWWEEKDAYS:"DSTQQSS".split(""),SHORTQUARTERS:["T1","T2","T3","T4"],QUARTERS:["1\u00ba trimestre",
"2\u00ba trimestre","3\u00ba trimestre","4\u00ba trimestre"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, d 'de' MMMM 'de' y","d 'de' MMMM 'de' y","d 'de' MMM 'de' y","dd/MM/y"],TIMEFORMATS:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],DATETIMEFORMATS:["{1} '\u00e0s' {0}","{1} '\u00e0s' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
var lub=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"];g.k=Ttb.prototype;g.k.XW=wub.FIRSTDAYOFWEEK;g.k.YW=wub.FIRSTWEEKCUTOFFDAY;g.k.clone=function(){var a=new Ttb(this.date);a.XW=this.XW;a.YW=this.YW;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.years||a.months){var b=this.getMonth()+a.months+12*a.years,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),x6(this,a.getDate()))};
g.k.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+Ptb(Math.abs(a),b?6:4),Ptb(this.getMonth()+1,2),Ptb(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var xub=new g.Tw("addUpcomingEventReminderEndpoint");var yub=new g.Tw("removeUpcomingEventReminderEndpoint");var zub=new g.Tw("updateUpcomingEventReminderButtonStateCommand");var Vtb=new g.Tw("upcomingEventReminderButtonRenderer"),aub=new g.Tw("upcomingEventReminderButtonStateRenderer");g.x(y6,g.jU);
y6.prototype.updateMenuItems=function(){var a=this,b=Utb(this),c=0;c=0;for(var d={};c<b.length;d={pY:void 0},c++){var e=this.j[c];e||(e=new g.V({I:"div",S:"ytp-reminder-menu-item",X:{role:"menuitem",tabindex:"0"},V:[{I:"div",S:"ytp-reminder-menu-item-icon",xa:"{{icon}}"},{I:"div",S:"ytp-reminder-menu-item-label",xa:"{{text}}"}]}),d.pY=c,e.listen("click",function(h){return function(){var l=h.pY;a.Lb();l=Utb(a)[l];a.publish("reminderMenuItemClicked",l.serviceEndpoint||l.command)}}(d)),e.Ia(this.items),
this.j[c]=e);
var f=b[c];d=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":d=Qtb();break;case "NOTIFICATIONS_NONE":d=Rtb();break;case "NOTIFICATIONS_ACTIVE":d=g.fxa()}f=f.text?g.GF(f.text):"";e.update({icon:d,text:f})}for(;c<this.j.length;)this.j.pop().dispose();0===c?this.Lb():this.rd(this.buttonElement)};
y6.prototype.hide=function(){this.buttonElement&&this.buttonElement.removeAttribute("aria-haspopup");g.jU.prototype.hide.call(this)};
y6.prototype.show=function(){this.buttonElement&&this.buttonElement.setAttribute("aria-haspopup","true");g.jU.prototype.show.call(this)};
y6.prototype.va=function(){g.wb(this.j);g.jU.prototype.va.call(this)};g.x(z6,g.V);
z6.prototype.G=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.C(a.toggledServiceEndpoint):this.C(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;A6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.Cb)this.j.Lb();else{var b=Ytb(this);b&&this.C(b.serviceEndpoint||b.command);b=(null==(a=g.U(null==b?void 0:b.command,g.pG))?void 0:a.commands)||[];a:{a=g.u(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=null==(b=g.U(c.value,
g.ekb))?void 0:null==(d=b.popup)?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new y6(this.J,this.buttonElement),this.j.Ia(this.element),g.O(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.C,this));b=this.j;b.menuPopupRenderer=a;b.updateMenuItems()}};
z6.prototype.C=function(a){var b=g.U(a,xub),c=g.U(a,yub);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for($tb(this,e,d.params),a=g.u(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.U(b,zub)){this.B=g.U(b,zub).state;A6(this);break}}};g.x(bub,g.V);g.k=bub.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.Ra=function(a){var b,c,d=null==a?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:c.offlineSlate;if(d){this.B=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.G1():cub(this,b);var e,f,h,l;if(c=null==a?void 0:null==(e=a.liveStreamability)?void 0:null==(f=e.liveStreamabilityRenderer)?void 0:null==(h=f.offlineSlate)?void 0:null==(l=h.liveStreamOfflineSlateRenderer)?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new z6(this.api),this.j.Ia(this.Ea("ytp-offline-slate-buttons")),g.O(this,this.j)),Wtb(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&Wtb(this.j,null,null);this.B=a}else this.B=null;this.K1()};
g.k.K1=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.Tb(),d=this.getVideoData();b=d.isLivePlayback&&(g.sL(c)||g.lG(c,2)||g.lG(c,64));var e=2===d.autonavState&&g.lG(c,2);c=c.isPlaying()&&!g.pT(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.B?this.Cb?(null==a?0:g.nG(a,2))&&!this.getVideoData().Sl&&(g.tv(this.element,"ytp-offline-slate-collapsed"),this.D.stop(),g.tv(this.C,"ytp-offline-slate-bar-fade"),this.G.start()):(this.show(),this.D.start(),this.api.publish("offlineslatestatechange"),
this.K&&this.api.AB()):this.Cb&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.k.G1=function(){var a,b,c,d,e=null==(a=this.B)?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:null==(d=c.offlineSlate)?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.kb()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(cub(this,e),this.countdownTimer.stop()):(cub(this,e,g.BG(b-a)),g.ev(this.countdownTimer)))};
g.k.va=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.V.prototype.va.call(this)};B6.prototype.B=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
B6.prototype.isExpired=function(){return 6E4<(0,g.ZC)()-this.C};
B6.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.x(kub,g.uV);g.k=kub.prototype;g.k.va=function(){F6(this);this.player.xf("heartbeat");g.uV.prototype.va.call(this)};
g.k.onCueRangeEnter=function(){this.N=!0;D6(this,2E3)};
g.k.cF=function(a){this.heartbeatParams=a;D6(this,2E3)};
g.k.y3=function(a){var b;8!==this.player.getPresentingPlayerType()&&"UNPLAYABLE"!==(null==(b=this.j)?void 0:b.status)&&(g.lG(a.state,2)||g.lG(a.state,64)?(F6(this),this.D&&(this.N=!0,D6(this,1E3))):(g.lG(a.state,1)||g.lG(a.state,8))&&D6(this,2E3))};
g.k.z3=function(){3!==this.player.getPresentingPlayerType()&&D6(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.xl=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.tJ=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.LC("heartbeatActionPlayerTransitioned",a)};
g.k.Bf=function(a){var b="LICENSE",c=nub(a);if(c)return c.reason||g.SV[b]||"";(a=a.match(oub))&&(a=Number(a[1]))&&(b=g.cDa(a));return g.SV[b]||""};
g.k.rE=function(){return!!this.offlineSlate&&this.offlineSlate.Cb};
var oub=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.tV("heartbeat",kub);})(_yt_player);
